// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO_23N1GtWYXp9EKoWALln7scgNaE1jxE',
    appId: '1:666743429550:web:994dbb369c0ec6e9d0503f',
    messagingSenderId: '666743429550',
    projectId: 'cverrajobrecruitmentplat-384d2',
    authDomain: 'cverrajobrecruitmentplat-384d2.firebaseapp.com',
    databaseURL: 'https://cverrajobrecruitmentplat-384d2-default-rtdb.firebaseio.com',
    storageBucket: 'cverrajobrecruitmentplat-384d2.firebasestorage.app',
    measurementId: 'G-ZQGVHCWVQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG73KW-LNY84Kz3Ly-6mP4IAP7H5zicPE',
    appId: '1:666743429550:android:57caa7be80c0136cd0503f',
    messagingSenderId: '666743429550',
    projectId: 'cverrajobrecruitmentplat-384d2',
    databaseURL: 'https://cverrajobrecruitmentplat-384d2-default-rtdb.firebaseio.com',
    storageBucket: 'cverrajobrecruitmentplat-384d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkkr_6H3Gw7mJAoT5mZ-iAlowI_BZmIA',
    appId: '1:666743429550:ios:bd39af45765f85c9d0503f',
    messagingSenderId: '666743429550',
    projectId: 'cverrajobrecruitmentplat-384d2',
    databaseURL: 'https://cverrajobrecruitmentplat-384d2-default-rtdb.firebaseio.com',
    storageBucket: 'cverrajobrecruitmentplat-384d2.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgkkr_6H3Gw7mJAoT5mZ-iAlowI_BZmIA',
    appId: '1:666743429550:ios:bd39af45765f85c9d0503f',
    messagingSenderId: '666743429550',
    projectId: 'cverrajobrecruitmentplat-384d2',
    databaseURL: 'https://cverrajobrecruitmentplat-384d2-default-rtdb.firebaseio.com',
    storageBucket: 'cverrajobrecruitmentplat-384d2.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO_23N1GtWYXp9EKoWALln7scgNaE1jxE',
    appId: '1:666743429550:web:c61a11ab4690b779d0503f',
    messagingSenderId: '666743429550',
    projectId: 'cverrajobrecruitmentplat-384d2',
    authDomain: 'cverrajobrecruitmentplat-384d2.firebaseapp.com',
    databaseURL: 'https://cverrajobrecruitmentplat-384d2-default-rtdb.firebaseio.com',
    storageBucket: 'cverrajobrecruitmentplat-384d2.firebasestorage.app',
    measurementId: 'G-XV9GQNBHJ7',
  );
}
